# simple cloudbuild.yaml file that
# echo's the current date and time

steps:
  # build the nodejs image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/gke-example/nodejs", "."]

  # push the image to the container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/gke-example/nodejs"]
