# simple cloudbuild.yaml file that

steps:
  # build the nodejs image
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "LOCATION=australia-southeast1"
      - "REPOSITORY=gke-project-repo"
      - "IMAGE=nodejs"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
        ".",
      ]

images:
  - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}"
