# simple cloudbuild.yaml file that
# echo's the current date and time

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["-c", 'echo "The time is $(date). This is a test."']
